# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors
#
# [colors.primary]
# foreground = "#575279"
# background = "#fcf1e1"
# dim_foreground = "#797593"
# bright_foreground = "#575279"
# [colors.cursor]
# text = "#575279"
# cursor = "#d7827d"
#
# [colors.vi_mode_cursor]
# text = "#575279"
# cursor = "#d7827d"
#
# [colors.search.matches]
# foreground = "#797593"
# background = "#f2e9e1"
#
# [colors.search.focused_match]
# foreground = "#faf4ed"
# background = "#d7827e"
#
# [colors.hints.start]
# foreground = "#797593"
# background = "#fffaf3"
#
# [colors.hints.end]
# foreground = "#9893a5"
# background = "#fffaf3"
#
# [colors.line_indicator]
# foreground = "None"
# background = "None"
#
# [colors.footer_bar]
# foreground = "#575279"
# background = "#fffaf3"
#
# [colors.selection]
# text = "#575279"
# background = "#dfdad9"
#
# [colors.normal]
# black = "#f2e9e1"
# red = "#b4637a"
# green = "#286983"
# yellow = "#ea9d34"
# blue = "#56949f"
# magenta = "#907aa9"
# cyan = "#d7827e"
# white = "#575279"
#
# [colors.bright]
# black = "#9893a5"
# red = "#b4637a"
# green = "#286983"
# yellow = "#ea9d34"
# blue = "#56949f"
# magenta = "#907aa9"
# cyan = "#d7827e"
# white = "#575279"
#
# [colors.dim]
# black = "#9893a5"
# red = "#b4637a"
# green = "#286983"
# yellow = "#ea9d34"
# blue = "#56949f"
# magenta = "#907aa9"
# cyan = "#d7827e"
# white = "#575279"


# Rose pine moon

# [colors.primary]
# foreground = "#e0def4"
# background = "#232136"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"
#
# [colors.cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.search.matches]
# foreground = "#908caa"
# background = "#393552"
#
# [colors.search.focused_match]
# foreground = "#232136"
# background = "#ea9a97"
#
# [colors.hints.start]
# foreground = "#908caa"
# background = "#2a273f"
#
# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#2a273f"
#
# [colors.line_indicator]
# foreground = "None"
# background = "None"
#
# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#2a273f"
#
# [colors.selection]
# text = "#e0def4"
# background = "#44415a"
#
# [colors.normal]
# black = "#393552"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"

[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark_medium.toml"
]

[cursor]
style = "Block"

[font]
size = 14.0

# [font.bold]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold"
#
# [font.bold_italic]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold Italic"
#
# [font.italic]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold Italic"
#
# [font.normal]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold"

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "0xProto Nerd Font Mono"
style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
option_as_alt = "Both"


[window.padding]
x = 8
y = 12

