# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors
#

[general]
import = [
    "~/dotfiles/alacritty/.config/alacritty/themes/themes/rose_pine_dawn.toml"
]

[cursor]
style = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

# [font.normal]
# family = "0xProto Nerd Font Mono"
# style = "Regular"
#
# [font.bold]
# family = "0xProto Nerd Font Mono"
# style = "Bold"
#
# [font.italic]
# family = "0xProto Nerd Font Mono"
# style = "Italic"
#
# [font.bold_italic]
# family = "0xProto Nerd Font Mono"
# style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
opacity = 0.98
startup_mode = "Windowed"
option_as_alt = "Both"


[window.padding]
x = 8
y = 12

