# Tmux Plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @resurrect-dir '~/.tmux/resurrect'

run '~/.tmux/plugins/tpm/tpm'

# Mouse
set-option -g mouse on

# Bindings

# visual mode + y -> copy selection to clipboard   
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Enter copy mode with VV
# 解除原本的 V key 可能的綁定
bind-key -n C-s copy-mode

# Swtich Windows with alt + jk or num
# bind-key -n m-j select-window -t+1
# bind-key -n m-k select-window -t-1

bind-key -n m-1 select-window -t1
bind-key -n m-2 select-window -t2
bind-key -n m-3 select-window -t3
bind-key -n m-4 select-window -t4
bind-key -n m-5 select-window -t5

# Move around panes with hjkl, or alt + lh
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -n m-h select-pane -L
bind-key -n m-l select-pane -R
bind-key -n m-j select-pane -D
bind-key -n m-k select-pane -U

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Use | and - to split a window vertically and horizontally instead of " and % respoectively
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Open ~/.tmux.conf in vim and reload settings on quit
unbind e
bind e new-window -n '~/.tmux.conf' "sh -c 'nvim ~/.tmux.conf && tmux source ~/.tmux.conf'"




# Use r to quickly reload tmux settings
unbind r
bind r \
	source-file ~/.tmux.conf \;\
	display 'Reloaded tmux config'

# Prefix + / to search
bind-key / copy-mode \; send-key ?

# Prefix + h to clear screen and history buffer
bind y \
    send-keys "C-c; clear && tmux clear-history" \;\
    send-keys "Enter" \;\
    display 'Screen cleared'


#############################
########## Settings
#############################

# vim-motion in copy mode
setw -g mode-keys vi

# fix vim mode switching delay
set -s escape-time 0


# Default shell
set-option -ga terminal-overrides ",alacritty:Tc"
set -g default-terminal "alacritty"

# Enable osc52 passthorugh
set -g set-clipboard on

# Refresh status line every 5 seconds - Good for when music is playing / update time etc
set -g status-interval 5

# Start window and pane indices at 1.
set -g base-index 1
set -g pane-base-index 0

# Length of tmux status line
set -g status-left-length 30
set -g status-right-length 150
set -g status-justify centre

set-option -g status "on"


# Set the history limit so we get lots of scrollback.
setw -g history-limit 50000000




# I don't know how the settings below work
# I don't know how the settings below work
# I don't know how the settings below work

# Default statusbar color
set-option -g status-style bg="#{@@main_bg}",fg=colour223 


# Message info
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# Writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

# Status bar #d7827e for light mode
set-option -g status-left "\
#[fg=colour7, bg=]#{?client_prefix,#[bg=##ea9a97],} ❐ CMD "

set-option -g status-right "   \
#[fg=colour109]  %H:%M "

# #ebbcba for light mode
set-window-option -g window-status-current-format "\
#[fg=colour237, bg=#A7C080]\
#[fg=colour239 bg=] #I* \
#[fg=colour239, bg=] #W \
#[fg=colour214 bg=]"

set-window-option -g window-status-format "\
#[fg=colour237,bg=,noitalics]\
#[fg=colour223,bg=] #I \
#[fg=colour223, bg=] #W \
#[fg=colour239, bg=]"

